name: isar_changesync
description: A new Flutter package project.
version: 0.0.2
homepage:

environment:
  sdk: '>=2.18.4 <3.0.0'

isar_version: &isar_version ^3.0.0

dependencies:
  isar: *isar_version
  collection: any

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.22.0
  mockito: ^5.3.2
  build_runner: ^2.3.2
  isar_generator: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core
